name: 'Deploy to Portainer'
description: 'Deploy services to Portainer using GitHub Actions'
author: 'Dat Nguyen (datntdev@outlook.com)'
branding:
  icon: layers
  color: blue

inputs:
  portainerHost:
    description: 'The host URL of the Portainer instance'
    required: true
  portainerApiKey:
    description: 'The API key for the Portainer instance'
    required: true
  portainerEnvId:
    description: 'The environment ID in Portainer where the stack will be deployed'
    required: true
  portainerStackName:
    description: 'The name of the stack to be deployed in Portainer'
    required: true
  portainerFilePath:
    description: 'The file path of the Docker Compose file to be deployed'
    required: true
  portainerEnvVars:
    description: 'Environment variables to be passed to the stack (optional)'
    required: false

runs:
  using: node20
  main: dist/index.js
