name: 'Update a Portainer stack'
description: 'Updates the stack definition in Portainer by using GitHub Actions'
branding:
  icon: layers
  color: blue

inputs:
  portainerStackName:
    description: 'The name of the stack to be deployed in Portainer'
    required: true
  portainerFilePath:
    description: 'The file path of the Docker Compose file to be deployed'
    required: true

secrets:
  portainerHost:
    description: 'The host URL of the Portainer instance'
    required: true
  portainerApiKey:
    description: 'The API key for the Portainer instance'
    required: true
  portainerEnvVars:
    description: 'Environment variables to be passed to the stack (optional)'
    required: false

runs:
  using: node22
  main: dist/index.js
